name: mind_grid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.8
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  widgetbook: ^3.9.0
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
